version: '3.8'
services:
  gin-api-service:
    # build:
    #   context: .
    image: localdev/gin-api-service:latest
    environment:
      - APP_ENV=test
    ports:
      - "8081:8080"
    networks:
      - gin-api-network

networks:
  gin-api-network:
    name: local_bridge
    external: true
