// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"gin-boot-starter/apis/controllers"
	"gin-boot-starter/infra/db"
	"gin-boot-starter/persistence/repository"
	"gin-boot-starter/services"
	"github.com/google/wire"
)

// Injectors from wire_injector.go:

func InitializeUserService() *services.UserService {
	sqlxDB := db.GetDBCon()
	userRepository := repository.NewUserRepository(sqlxDB)
	userService := services.NewUserService(userRepository)
	return userService
}

func InitializeAclService() *services.AclService {
	sqlxDB := db.GetDBCon()
	aclRepository := repository.NewAclRepository(sqlxDB)
	aclService := services.NewAclService(aclRepository)
	return aclService
}

// wire_injector.go:

// reuseable
var dbSet = wire.NewSet(db.GetDBCon)

var aclServiceSet = wire.NewSet(dbSet, repository.NewAclRepository, services.NewAclService)

// reuseable
var userServiceSet = wire.NewSet(dbSet, repository.NewUserRepository, services.NewUserService)

// InitializeUserController injector
func InitializeUserController() *controllers.UserController {
	return controllers.NewUserController(InitializeUserService())
}

func InitializeAccountController() *controllers.AccountController {
	return controllers.NewAccountController(InitializeUserService(), InitializeAclService())
}
