// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"gin001/apis/controllers"
	"gin001/infra/db"
	"gin001/persistence/repository"
	"gin001/services"
	"github.com/google/wire"
)

// Injectors from wire_injector.go:

// InitializeUserController injector
func InitializeUserController() *controllers.UserController {
	sqlxDB := db.GetDBCon()
	userRepository := repository.NewUserRepository(sqlxDB)
	userService := services.NewUserService(userRepository)
	userController := controllers.NewUserController(userService)
	return userController
}

// wire_injector.go:

var dbSet = wire.NewSet(db.GetDBCon)

// UserControllerSet of dependencies
var UserControllerSet = wire.NewSet(dbSet, repository.NewUserRepository, services.NewUserService, controllers.NewUserController)
