BEGIN;

CREATE TABLE IF NOT EXISTS casbin_rule (
    id SERIAL PRIMARY KEY,
    ptype VARCHAR(100),
    v0 VARCHAR(100),
    v1 VARCHAR(100),
    v2 VARCHAR(100),
    v3 VARCHAR(100),
    v4 VARCHAR(100),
    v5 VARCHAR(100)
);

ALTER TABLE users ADD COLUMN hashed_password text DEFAULT "";
ALTER TABLE users ADD COLUMN roles text DEFAULT "";

COMMIT;